import { CommonModule, CurrencyPipe, DatePipe } from '@angular/common';
import { Component, OnDestroy, OnInit, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpErrorResponse } from '@angular/common/http';
import { interval, of, Subject, switchMap, takeUntil, catchError, tap } from 'rxjs';
import { SalesService } from '@commercial/sales/services/sales.service';
import { RecipeService } from '@commercial/sales/services/recipe.service';
import { RestaurantTable, RestaurantTableService } from '@commercial/sales/services/restaurant-table.service';
import { Seller, SellerService } from '@commercial/sales/services/seller.service';
import { ENV } from '@config/env.config';
import { RecipePreparationTrace, SaleRequest, SaleResponse, SaleStatus } from '@commercial/sales/models/sale.model';
import { RecipeResponse, SaleableRecipe } from '@commercial/sales/models/recipe.model';

type StatusFilter = 'ALL' | 'ACTIVE' | 'INACTIVE';
type VisibilityFilter = 'ALL' | 'VISIBLE' | 'HIDDEN';
type SortMode = 'NAME_ASC' | 'PRICE_ASC' | 'PRICE_DESC';
interface CartLine { recipeId: string; recipeName: string; lineDisplayName: string; quantity: number; unitPrice: number; recipeLineComment: string; }
@Component({ selector: 'app-sales-pos-page', standalone: true, imports: [CommonModule, FormsModule, CurrencyPipe, DatePipe], templateUrl: './sales-pos-page.html', styleUrl: './sales-pos-page.css' })
export class SalesPosPage implements OnInit, OnDestroy {
private readonly salesService = inject(SalesService); private readonly recipeService = inject(RecipeService); private readonly tableService = inject(RestaurantTableService); private readonly sellerService = inject(SellerService); private readonly destroy$ = new Subject<void>();
readonly recipes = signal<SaleableRecipe[]>([]); readonly recipeNameById = signal<Record<string, string>>({}); readonly sales = signal<SaleResponse[]>([]); readonly currentCart = signal<CartLine[]>([]);
readonly searchQuery = signal(''); readonly statusFilter = signal<StatusFilter>('ALL'); readonly visibilityFilter = signal<VisibilityFilter>('ALL'); readonly minPrice = signal<number | null>(null); readonly maxPrice = signal<number | null>(null); readonly sortMode = signal<SortMode>('NAME_ASC');
readonly selectedSellerName = signal('Selecciona un vendedor'); readonly selectedSellerId = signal(''); readonly availableSellers = signal<Seller[]>([]); readonly sellerSelectorOpen = signal(false); readonly loadingSellers = signal(false); readonly sellerQuery = signal('');
readonly selectedLocationId = signal(ENV.locationId); readonly selectedTableId = signal<string | null>(null); readonly selectedTableLabel = signal('Selecciona una mesa'); readonly availableTables = signal<RestaurantTable[]>([]); readonly tableSelectorOpen = signal(false); readonly loadingTables = signal(false);
readonly loadingRecipes = signal(false); readonly loadingSales = signal(false); readonly submitting = signal(false); readonly recipeError = signal(false); readonly processingSaleIds = signal<string[]>([]); readonly preparationTracesBySaleId = signal<Record<string, RecipePreparationTrace[]>>({});
readonly toastMessage = signal(''); readonly toastType = signal<'success'|'error'|'warning'|'info'>('success'); readonly toastProgress = signal(100); private toastTimer?: ReturnType<typeof setTimeout>;
readonly filteredRecipes = computed(() => this.recipes().filter(i => (!this.searchQuery() || i.name.toLowerCase().includes(this.searchQuery().toLowerCase().trim())) && (this.statusFilter()==='ALL' || (this.statusFilter()==='ACTIVE'?i.active:!i.active)) && (this.visibilityFilter()==='ALL' || (this.visibilityFilter()==='VISIBLE'?i.visibleInMenu:!i.visibleInMenu)) && (this.minPrice()===null || i.price>=this.minPrice()!) && (this.maxPrice()===null || i.price<=this.maxPrice()!)).sort((a,b)=>this.sortMode()==='PRICE_ASC'?a.price-b.price:this.sortMode()==='PRICE_DESC'?b.price-a.price:a.name.localeCompare(b.name,'es')));
ngOnInit(){this.loadRecipes();this.refreshSales();this.loadSellers();} ngOnDestroy(){this.destroy$.next();this.destroy$.complete();}
computeTotal(){return this.currentCart().reduce((a,l)=>a+l.quantity*l.unitPrice,0)} cartItemsCount(){return this.currentCart().reduce((a,l)=>a+l.quantity,0)}
addToCart(item: SaleableRecipe){ if(!item.active)return this.pushToast('warning','No puedes vender una receta inactiva.'); if(!item.price||item.price<=0)return this.pushToast('warning','Precio no disponible para esta receta.'); this.currentCart.update(c=>{const idx=c.findIndex(x=>x.recipeId===item.id); if(idx===-1)return [...c,{recipeId:item.id,recipeName:item.name,lineDisplayName:item.name,quantity:1,unitPrice:item.price,recipeLineComment:'Sin observaciones'}]; const n=[...c]; n[idx]={...n[idx],quantity:n[idx].quantity+1}; return n;}); }
updateQuantity(id:string,q:number){this.currentCart.update(c=>c.map(x=>x.recipeId===id?{...x,quantity:Math.max(1,q||1)}:x));} removeFromCart(id:string){this.currentCart.update(c=>c.filter(x=>x.recipeId!==id));} updateComment(id:string,v:string){this.currentCart.update(c=>c.map(x=>x.recipeId===id?{...x,recipeLineComment:(v||'Sin observaciones').trim()||'Sin observaciones'}:x));}
openTableSelector(){this.tableSelectorOpen.set(true); if(this.availableTables().length>0)return; this.loadingTables.set(true); this.tableService.getTables().subscribe({next:t=>{this.availableTables.set(t);this.loadingTables.set(false);},error:()=>{this.loadingTables.set(false);this.pushToast('error','No se pudieron cargar las mesas.');}})}
closeTableSelector(){this.tableSelectorOpen.set(false);} selectTable(t:RestaurantTable){if(!this.isTableAvailable(t))return this.pushToast('warning','Debes seleccionar una mesa disponible.'); this.selectedTableId.set(t.id); this.selectedTableLabel.set(this.tableLabel(t)); this.pushToast('success','Mesa seleccionada correctamente.'); this.closeTableSelector();}
openSellerSelector(){this.sellerSelectorOpen.set(true);} closeSellerSelector(){this.sellerSelectorOpen.set(false);} filteredSellers(){const q=this.sellerQuery().toLowerCase().trim(); return this.availableSellers().filter(s=>!q||this.sellerDisplayName(s).toLowerCase().includes(q)||(s.document??'').toLowerCase().includes(q));}
selectSeller(s:Seller){if(!this.isSellerActive(s))return; this.selectedSellerId.set(s.id); this.selectedSellerName.set(this.sellerDisplayName(s)); this.pushToast('success','Vendedor seleccionado correctamente.'); this.closeSellerSelector();}
completeSale(){const payload=this.buildPayload(); if(!payload)return; this.submitting.set(true); this.salesService.createSale(payload).subscribe({next:r=>{this.submitting.set(false);this.pushToast('success','Venta creada correctamente.');this.currentCart.set([]);this.trackProcessing(r.saleId,'create');this.refreshSales();},error:e=>{this.submitting.set(false);this.pushToast('error',this.readError(e));}})}
refreshPreparations(saleId:string){this.salesService.getSalePreparations(saleId).subscribe({next:t=>{this.preparationTracesBySaleId.update(s=>({...s,[saleId]:t})); if(t.some(x=>x.status==='REJECTED'))this.pushToast('warning','Una o más recetas fueron rechazadas por inventario.');},error:()=>this.pushToast('error','No se pudo cargar la trazabilidad.')});}
buildPayload(){ if(!this.selectedSellerId()) return this.pushToast('warning','Debes seleccionar un vendedor.'),null; if(!this.selectedTableId()) return this.pushToast('warning','Debes seleccionar una mesa disponible.'),null; if(!this.selectedLocationId()) return this.pushToast('error','Sede obligatoria.'),null; if(this.currentCart().length===0) return this.pushToast('error','Agrega recetas para iniciar una venta.'),null; return {sellerId:this.selectedSellerId(),locationId:this.selectedLocationId(),tableId:this.selectedTableId()!,details:this.currentCart().map(l=>({recipeId:l.recipeId,quantity:l.quantity,unitPrice:l.unitPrice,recipeLineComment:l.recipeLineComment||'Sin observaciones',lineDisplayName:l.lineDisplayName||l.recipeName}))} as SaleRequest; }
shortSaleCode(id:string){return `Venta #${id.slice(-6).toUpperCase()}`;} saleStatusLabel(s:SaleStatus){return({CREATED:'Creada',IN_PROGRESS:'En proceso',COMPLETED:'Completada',CANCELLED:'Cancelada'})[s];} traceStatusLabel(s:'ACCEPTED'|'REJECTED'){return s==='ACCEPTED'?'Aceptada':'Rechazada';} traceRecipeName(id:string){return this.recipeNameById()[id]??'Receta no encontrada';}
canPatchTo(c:SaleStatus|undefined,t:SaleStatus){if(!c)return false; if(c==='CREATED')return t==='IN_PROGRESS'||t==='CANCELLED'; if(c==='IN_PROGRESS')return t==='COMPLETED'||t==='CANCELLED'; return false;} isProcessing(id:string){return this.processingSaleIds().includes(id);} tracesBySaleId(id:string){return this.preparationTracesBySaleId()[id]??[];}
isTableAvailable(t:RestaurantTable){if(t.available!==undefined)return t.available; if(t.occupied!==undefined)return !t.occupied; if(t.status)return ['AVAILABLE','DISPONIBLE','FREE','LIBRE'].includes(t.status.toUpperCase()); return true;} tableLabel(t:RestaurantTable){return t.name||(t.number?`Mesa ${t.number}`:t.code||'Mesa sin nombre');}
isSellerActive(s:Seller){if(s.active!==undefined)return s.active; if(s.status)return !['INACTIVE','DISABLED'].includes(s.status.toUpperCase()); return true;} sellerDisplayName(s:Seller){return s.fullName||s.name||`${s.firstName??''} ${s.lastName??''}`.trim()||'Vendedor sin nombre';}
patchStatus(id:string,status:SaleStatus){if(!this.canPatchTo(this.sales().find(s=>s.id===id)?.status,status))return; this.salesService.patchSaleStatus(id,status).subscribe({next:()=>{this.pushToast('info','Cambio de estado enviado a procesamiento.');this.trackProcessing(id,'patch');},error:e=>this.pushToast('error',this.readError(e))});}
deleteSale(s:SaleResponse){if(s.status==='COMPLETED')return this.pushToast('warning','No se puede eliminar una venta completada.'); this.salesService.deleteSale(s.id).subscribe({next:()=>{this.pushToast('info','Eliminación solicitada. Se está procesando con inventario.');this.trackProcessing(s.id,'delete');},error:e=>this.pushToast('error',this.readError(e))});}
private refreshSales(){this.loadingSales.set(true);this.salesService.getSales().subscribe({next:s=>{this.sales.set(s??[]);this.loadingSales.set(false);},error:e=>{this.loadingSales.set(false);this.pushToast('error',this.readLoadSalesError(e));}})}
private loadRecipes(){this.loadingRecipes.set(true);this.recipeError.set(false);this.recipeService.getRecipes().subscribe({next:(r:RecipeResponse[])=>{this.recipes.set(r.map(x=>({id:x.id,name:x.name,price:x.sellingPrice,active:x.active,visibleInMenu:x.visibleInMenu})));this.recipeNameById.set(r.reduce((a,c)=>({...a,[c.id]:c.name}),{}));this.loadingRecipes.set(false);},error:()=>{this.loadingRecipes.set(false);this.recipeError.set(true);this.pushToast('error','No se pudieron cargar las recetas.');}})}
private loadSellers(){this.loadingSellers.set(true); this.sellerService.getSellers().subscribe({next:s=>{this.availableSellers.set(s??[]);this.loadingSellers.set(false);},error:()=>{this.loadingSellers.set(false);this.pushToast('warning','No se pudieron cargar los vendedores.');}})}
private trackProcessing(saleId:string,mode:'create'|'patch'|'delete'){this.processingSaleIds.update(ids=>ids.includes(saleId)?ids:[...ids,saleId]);const startedAt=Date.now();interval(3000).pipe(takeUntil(this.destroy$),switchMap(()=>this.salesService.getSaleById(saleId).pipe(catchError((e:HttpErrorResponse)=>of(e)))),tap((result)=>{const timeout=Date.now()-startedAt>60000;if(result instanceof HttpErrorResponse&&result.status===404&&!timeout)return;if(timeout){this.pushToast('warning',`La ${mode==='delete'?'eliminación':'venta'} sigue en procesamiento.`);return this.stopTracking(saleId);}if(result instanceof HttpErrorResponse){this.pushToast('error',this.readError(result));return this.stopTracking(saleId);}if(mode!=='delete'){this.refreshSales();this.refreshPreparations(saleId);}this.stopTracking(saleId);})).subscribe();}
private stopTracking(saleId:string){this.processingSaleIds.update(ids=>ids.filter(id=>id!==saleId));}
private pushToast(type:'success'|'error'|'warning'|'info',message:string){this.toastType.set(type);this.toastMessage.set(message);this.toastProgress.set(100);if(this.toastTimer)clearTimeout(this.toastTimer);const started=Date.now();const total=4500;const progressInterval=setInterval(()=>{const elapsed=Date.now()-started;this.toastProgress.set(Math.max(0,100-(elapsed/total)*100));if(elapsed>=total)clearInterval(progressInterval);},100);this.toastTimer=setTimeout(()=>{this.toastMessage.set('');this.toastProgress.set(0);clearInterval(progressInterval);},total);}
closeToast(){if(this.toastTimer)clearTimeout(this.toastTimer);this.toastMessage.set('');this.toastProgress.set(0);} private readLoadSalesError(error:unknown){const err=error as HttpErrorResponse; if(err.status===0)return'No se pudo conectar con el servidor.';if(err.status===401)return'Sesión expirada. Inicia sesión nuevamente.';return'No se pudieron cargar las ventas.';} private readError(error:unknown){const err=error as HttpErrorResponse; return err.error?.message??'No se pudo crear la venta.';}
}
